# Copyright (c) Universidade Federal Fluminense (UFF).
# This file is part of SAPOS. Please, consult the license terms in the LICENSE file.

# frozen_string_literal: true

Institution.create([
  { name: "Associação de Ensino Superior do Piauí", code: "AESPI" },
  { name: "Centro Federal de Educação Tecnológica C S F", code: "CEFET-RJ" },
  { name: "Centro Universitário Luterano de Palmas", code: "CEULP" },
  { name: "Centro Federal de Educação Tecnológica de Campos", code: "CFETC" },
  { name: "Escola Federal de Engenharia de", code: "EFEI" },
  { name: "Escola Naval", code: "EM" },
  { name: "Faculdade Integral Diferencial", code: "FACID" },
  { name: "Faculdades Integradas de Rondonópolis", code: "FAIR" },
  { name: "Faculdade Carioca", code: "FC" },
  { name: "Faculdade da Cidade", code: "FCIDADE" },
  { name: "Fundação Educacional de Barretos", code: "FEB" },
  { name: "Fundação Educacional Souza Marques", code: "FESM" },
  { name: "Federação das Faculdades Celso Lisboa", code: "FFCL" },
  { name: "Fundação Getúlio Vargas", code: "FGV" },
  { name: "Faculdades Integradas Anglo-Americano", code: "FIAA" },
  { name: "Faculdades Integradas de Caratinga", code: "FIC" },
  { name: "Faculdades Integradas Maria Teresa", code: "FMT" },
  { name: "Fundação Universidade Federal do Tocantins", code: "FUFTO" },
  { name: "Instituto de Estudos superiores da Amazônia", code: "IESA" },
  { name: "Instituto Federal do Piauí", code: "IFPI" },
  { name: "Instituto Militar de Engenharia", code: "IME" },
  { name: "Instituto Metodista Granbery", code: "IMG" },
  { name: "Instituto Nacional de Telecomunicações", code: "INATEL" },
  { name: "Instituto Superior de Tecnol em Ciência da Comp", code: "ISTCC" },
  { name: "Instituto Tecnológico da Aeronáutica", code: "ITA" },
  { name: "Faculdades Reunidas Nuno Lisboa", code: "NUNO" },
  { name: "Pontifícia Universidade Católica de Minas Gerais", code: "PUC/MG" },
  { name: "Pontifícia Universid Católica do Rio Grande do Sul", code: "PUC/RS" },
  { name: "Pontifícia Universidade Católica do Rio de Janeiro", code: "PUC-RJ" },
  { name: "Sociedade de Ensino Sup. E Assessoria Técnica", code: "SESAT" },
  { name: "Sociedade dos Amigos dos Militares", code: "SUAM" },
  { name: "Universidade de Barra Mansa", code: "UBM" },
  { name: "Universidade Católica Dom Bosco", code: "UCDB" },
  { name: "Universidade Católica de Goiás", code: "UCG" },
  { name: "Universidade Cândido Mendes", code: "UCM" },
  { name: "Universidade Católica de Petrópolis", code: "UCP" },
  { name: "Universidade Católica de Santa Maria", code: "UCSM" },
  { name: "Universidade Estadual do Norte-Fluminense", code: "UENF" },
  { name: "Universidade Estadual do Piauí", code: "UEPI" },
  { name: "Universidade Estadual do Rio de Janeiro", code: "UERJ" },
  { name: "Universidade Federal de Alagoas", code: "UFA" },
  { name: "Universidade Federal da Bahia", code: "UFBA" },
  { name: "Universidade Federal do Ceará", code: "UFC" },
  { name: "Univeridade Federal Campina Grande", code: "UFCG" },
  { name: "Universidade Federal do Espírito Santo", code: "UFES" },
  { name: "Universidade Federal Fluminense", code: "UFF" },
  { name: "Universidade Federal de Goiás", code: "UFGo" },
  { name: "Universidade Federal de Juiz de Fora", code: "UFJF" },
  { name: "Universidade Federal de Lavras", code: "UFLA" },
  { name: "Universidade Federal de Minas Gerais", code: "UFMG" },
  { name: "Universidade Federal de Mato Grosso", code: "UFMT" },
  { name: "Universidade de Fortaleza", code: "UFO" },
  { name: "Universidade Federal de Ouro Preto", code: "UFOP" },
  { name: "Universidade Federal do Pará", code: "UFP" },
  { name: "Universidade Federal da Paraíba", code: "UFPB" },
  { name: "Universidade Federal de Pernambuco", code: "UFPE" },
  { name: "Universidade Federal do Piauí", code: "UFPI" },
  { name: "Universidade Federal do Paraná", code: "UFPR" },
  { name: "Universidade Federal do Rio de Janeiro", code: "UFRJ" },
  { name: "Universidade Federal do Rio Grande do Norte", code: "UFRN" },
  { name: "Universidade Federal Rural do Rio de Janeiro", code: "UFRRJ" },
  { name: "Universidade Federal de Santa Catarina", code: "UFSC" },
  { name: "Universidade Federal Santa Maria", code: "UFSM" },
  { name: "Universidade Federal do Tocantins", code: "UFT" },
  { name: "Universidade  Federal de Viçosa", code: "UFV" },
  { name: "Universidade Gama Filho", code: "UGF" },
  { name: "Universidade do Grande Rio", code: "UGR" },
  { name: "Universidade Luterana do Brasil", code: "ULBRA" },
  { name: "Universidade de Lima (Peru)", code: "ULIMA" },
  { name: "Universidade da Amazônia", code: "UNAMA" },
  { name: "Universidad Nacional del Callao", code: "UNC" },
  { name: "Universidade Estácio de Sá", code: "UNESA" },
  { name: "Universidade Estadual de Campinas", code: "UNICAMP" },
  { name: "Universidade Salvador", code: "UNIFACS" },
  { name: "Universidade Federal de Itajubá", code: "UNIFEI" },
  { name: "Centro Universitário Serra dos Órgãos", code: "UNIFESO" },
  { name: "Universidade Presidente Antônio Carlos", code: "UNIPAC" },
  { name: "Universidade Federal do Estado do Rio de Janeiro", code: "UNIRIO" },
  { name: "Universidade Vale do Rio Doce", code: "UNIVALE" },
  { name: "Universidad Nacional de San antonio Abad del Cusco", code: "UNSAAC" },
  { name: "Universidad Nacional de Trujillo", code: "UNT" },
  { name: "Universidad Ricardo Palma", code: "URP" },
  { name: "Universidade de São Paulo", code: "USP" },
  { name: "Universidade Silva e Souza", code: "USS" },
  { name: "Universidade Santa Úrsula", code: "USU" },
  { name: "Universidade Veiga de Almeida", code: "UVA" },
])
