class AddNationalityToCountry < ActiveRecord::Migration
  def change
  	add_column :countries, :nationality, :string, :default => "-"

  	Country.where(:name=>"Afeganistão").first.update(:nationality=>"afegã(o)")
		Country.where(:name=>"África do Sul").first.update(:nationality=>"sul-africano(a)")
		Country.where(:name=>"Albânia, República da").first.update(:nationality=>"albanês(esa)")
		Country.where(:name=>"Alemanha").first.update(:nationality=>"alemã(ão)")
		Country.where(:name=>"Andorra").first.update(:nationality=>"andorrano(a)")
		Country.where(:name=>"Angola").first.update(:nationality=>"angolano(a)")
		Country.where(:name=>"Anguilla").first.update(:nationality=>"anguilano(a)")
		Country.where(:name=>"Antigua e Barbuda").first.update(:nationality=>"antiguano(a)")
		Country.where(:name=>"Antilhas Holandesas").first.update(:nationality=>"-")
		Country.where(:name=>"Arábia Saudita").first.update(:nationality=>"árabe-saudita")
		Country.where(:name=>"Argélia").first.update(:nationality=>"argelino(a)")
		Country.where(:name=>"Argentina").first.update(:nationality=>"argentino(a)")
		Country.where(:name=>"Armênia, República da").first.update(:nationality=>"arménio(a)")
		Country.where(:name=>"Aruba").first.update(:nationality=>"arubano(a)")
		Country.where(:name=>"Austrália").first.update(:nationality=>"australiano(a)")
		Country.where(:name=>"Áustria").first.update(:nationality=>"austríaco(a)")
		Country.where(:name=>"Azerbaijão, Repúblicado").first.update(:nationality=>"azeri")
		Country.where(:name=>"Bahamas, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Bahrein, Ilhas").first.update(:nationality=>"barenita")
		Country.where(:name=>"Bangladesh").first.update(:nationality=>"-")
		Country.where(:name=>"Barbados").first.update(:nationality=>"barbadense")
		Country.where(:name=>"Belarus").first.update(:nationality=>"bielo-russa")
		Country.where(:name=>"Bélgica").first.update(:nationality=>"belga")
		Country.where(:name=>"Belize").first.update(:nationality=>"belizenho(a)")
		Country.where(:name=>"Benin").first.update(:nationality=>"benineseo(a)")
		Country.where(:name=>"Bermudas").first.update(:nationality=>"-")
		Country.where(:name=>"Bolívia").first.update(:nationality=>"boliviano(a)")
		Country.where(:name=>"Bósnia-Herzegovina").first.update(:nationality=>"bósnio(a)")
		Country.where(:name=>"Botsuana").first.update(:nationality=>"-")
		Country.where(:name=>"Brasil").first.update(:nationality=>"brasileiro(a)")
		Country.where(:name=>"Brunei").first.update(:nationality=>"-")
		Country.where(:name=>"Bulgária, República da").first.update(:nationality=>"búlgaro(a)")
		Country.where(:name=>"Burkina Faso").first.update(:nationality=>"-")
		Country.where(:name=>"Burundi").first.update(:nationality=>"-")
		Country.where(:name=>"Butão").first.update(:nationality=>"-")
		Country.where(:name=>"Cabo Verde, República de").first.update(:nationality=>"Cabo Verde cabo-verdiano(a)")
		Country.where(:name=>"Camarões").first.update(:nationality=>"-")
		Country.where(:name=>"Camboja").first.update(:nationality=>"cambojano(a)")
		Country.where(:name=>"Canadá").first.update(:nationality=>"canadiano(a)")
		Country.where(:name=>"Canal, Ilhas do (Jerseye Guernsey)").first.update(:nationality=>"-")
		Country.where(:name=>"Canárias, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Catar").first.update(:nationality=>"-")
		Country.where(:name=>"Cayman, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Cazaquistão, República do").first.update(:nationality=>"-")
		Country.where(:name=>"Chade").first.update(:nationality=>"-")
		Country.where(:name=>"Chile").first.update(:nationality=>"chileno(a)")
		Country.where(:name=>"China, República Popular da").first.update(:nationality=>"chinês(esa)")
		Country.where(:name=>"Chipre").first.update(:nationality=>"cipriota")
		Country.where(:name=>"Christmas, Ilha (Navidad)").first.update(:nationality=>"-")
		Country.where(:name=>"Cingapura").first.update(:nationality=>"-")
		Country.where(:name=>"Cocos (Keeling), Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Colômbia").first.update(:nationality=>"colombiano(a)")
		Country.where(:name=>"Comores, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Congo, República Democrática do").first.update(:nationality=>"-")
		Country.where(:name=>"Congo, República do").first.update(:nationality=>"Congo congolês(a)")
		Country.where(:name=>"Cook, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Coréia, Rep. Pop. Democrática da").first.update(:nationality=>"-")
		Country.where(:name=>"Coréia, República da").first.update(:nationality=>"sul-coreano(a)")
		Country.where(:name=>"Costa do Marfim").first.update(:nationality=>"Costa do Marfm marfinense")
		Country.where(:name=>"Costa Rica").first.update(:nationality=>"costa-riquenho(a)")
		Country.where(:name=>"Coveite").first.update(:nationality=>"-")
		Country.where(:name=>"Croácia, República da").first.update(:nationality=>"croata")
		Country.where(:name=>"Cuba").first.update(:nationality=>"cubano(a)")
		Country.where(:name=>"Dinamarca").first.update(:nationality=>"dinamarquês(esa)")
		Country.where(:name=>"Djibuti").first.update(:nationality=>"-")
		Country.where(:name=>"Dominica, Ilha").first.update(:nationality=>"dominiquês(esa)")
		Country.where(:name=>"Egito").first.update(:nationality=>"egípcio(a)")
		Country.where(:name=>"ElSalvador").first.update(:nationality=>"-")
		Country.where(:name=>"Emirados Árabes Unidos").first.update(:nationality=>"emiradense")
		Country.where(:name=>"Equador").first.update(:nationality=>"equatoriano(a)")
		Country.where(:name=>"Eritréia").first.update(:nationality=>"-")
		Country.where(:name=>"Escócia").first.update(:nationality=>"escocês(esa)")
		Country.where(:name=>"Eslovaca, República").first.update(:nationality=>"-")
		Country.where(:name=>"Eslovênia, República da").first.update(:nationality=>"Eslovénia esloveno(a)")
		Country.where(:name=>"Espanha").first.update(:nationality=>"espanhol(a)")
		Country.where(:name=>"Estados Unidos").first.update(:nationality=>"norte-americano(a)")
		Country.where(:name=>"Estônia, República da").first.update(:nationality=>"-")
		Country.where(:name=>"Etiópia").first.update(:nationality=>"etíope")
		Country.where(:name=>"Falkland (Ilhas Malvinas)").first.update(:nationality=>"-")
		Country.where(:name=>"Feroe, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Fiji").first.update(:nationality=>"-")
		Country.where(:name=>"Filipinas").first.update(:nationality=>"filipino")
		Country.where(:name=>"Finlândia").first.update(:nationality=>"finlandês(esa)")
		Country.where(:name=>"Formosa (Taiwan)").first.update(:nationality=>"-")
		Country.where(:name=>"França").first.update(:nationality=>"francês(esa)")
		Country.where(:name=>"Gabão").first.update(:nationality=>"-")
		Country.where(:name=>"Gales, País de").first.update(:nationality=>"-")
		Country.where(:name=>"Gâmbia").first.update(:nationality=>"gambiano(a)")
		Country.where(:name=>"Gana").first.update(:nationality=>"ganês(a)")
		Country.where(:name=>"Geórgia, República da").first.update(:nationality=>"georgiano(a)")
		Country.where(:name=>"Gibraltar").first.update(:nationality=>"-")
		Country.where(:name=>"Grã-Bretanha").first.update(:nationality=>"-")
		Country.where(:name=>"Granada").first.update(:nationality=>"-")
		Country.where(:name=>"Grécia").first.update(:nationality=>"grego(a)")
		Country.where(:name=>"Groenlândia").first.update(:nationality=>"-")
		Country.where(:name=>"Guadalupe").first.update(:nationality=>"guadalupense")
		Country.where(:name=>"Guam").first.update(:nationality=>"-")
		Country.where(:name=>"Guatemala").first.update(:nationality=>"guatemalteco(a)")
		Country.where(:name=>"Guiana").first.update(:nationality=>"-")
		Country.where(:name=>"Guiana Francesa").first.update(:nationality=>"-")
		Country.where(:name=>"Guiné").first.update(:nationality=>"-")
		Country.where(:name=>"Guiné-Bissau").first.update(:nationality=>"-")
		Country.where(:name=>"Guiné-Equatorial").first.update(:nationality=>"-")
		Country.where(:name=>"Haiti").first.update(:nationality=>"-")
		Country.where(:name=>"Holanda (PaísesBaixos)").first.update(:nationality=>"-")
		Country.where(:name=>"Honduras").first.update(:nationality=>"hondurenho(a)")
		Country.where(:name=>"HongKong, Região Adm. Especial").first.update(:nationality=>"honconguês(esa)")
		Country.where(:name=>"Hungria, Repúblicada").first.update(:nationality=>"húngaro(a)")
		Country.where(:name=>"Iêmen").first.update(:nationality=>"-")
		Country.where(:name=>"Índia").first.update(:nationality=>"indiano(a)")
		Country.where(:name=>"Indonésia").first.update(:nationality=>"indonésio")
		Country.where(:name=>"Inglaterra").first.update(:nationality=>"inglês(esa)")
		Country.where(:name=>"Irã, República Islâmica do").first.update(:nationality=>"Irã iraniano(a)")
		Country.where(:name=>"Iraque").first.update(:nationality=>"iraquiano(a)")
		Country.where(:name=>"Irlanda").first.update(:nationality=>"irlandês(a)")
		Country.where(:name=>"Irlanda do Norte").first.update(:nationality=>"norte irlandês(a)")
		Country.where(:name=>"Islândia").first.update(:nationality=>"islandês(esa)")
		Country.where(:name=>"Israel").first.update(:nationality=>"israelita")
		Country.where(:name=>"Itália").first.update(:nationality=>"italiano(a)")
		Country.where(:name=>"Iugoslávia, República Fed. da").first.update(:nationality=>"-")
		Country.where(:name=>"Jamaica").first.update(:nationality=>"-")
		Country.where(:name=>"Japão").first.update(:nationality=>"-")
		Country.where(:name=>"Johnston, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Jordânia").first.update(:nationality=>"-")
		Country.where(:name=>"Kiribati").first.update(:nationality=>"-")
		Country.where(:name=>"Laos, Rep. Pop. Democrática do").first.update(:nationality=>"laociano(a)")
		Country.where(:name=>"Lebuan").first.update(:nationality=>"-")
		Country.where(:name=>"Lesoto").first.update(:nationality=>"-")
		Country.where(:name=>"Letônia, Repúblicada").first.update(:nationality=>"-")
		Country.where(:name=>"Líbano").first.update(:nationality=>"-")
		Country.where(:name=>"Libéria").first.update(:nationality=>"-")
		Country.where(:name=>"Líbia").first.update(:nationality=>"líbio(a)")
		Country.where(:name=>"Liechtenstein").first.update(:nationality=>"-")
		Country.where(:name=>"Lituânia, República da").first.update(:nationality=>"lituano(a)")
		Country.where(:name=>"Luxemburgo").first.update(:nationality=>"-")
		Country.where(:name=>"Macau").first.update(:nationality=>"-")
		Country.where(:name=>"Macedônia").first.update(:nationality=>"-")
		Country.where(:name=>"Madagascar").first.update(:nationality=>"-")
		Country.where(:name=>"Madeira, Ilhada").first.update(:nationality=>"-")
		Country.where(:name=>"Malásia").first.update(:nationality=>"-")
		Country.where(:name=>"Malavi").first.update(:nationality=>"-")
		Country.where(:name=>"Maldivas").first.update(:nationality=>"-")
		Country.where(:name=>"Máli").first.update(:nationality=>"maliano")
		Country.where(:name=>"Malta").first.update(:nationality=>"-")
		Country.where(:name=>"Man, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Marianas do Norte").first.update(:nationality=>"-")
		Country.where(:name=>"Marrocos").first.update(:nationality=>"marroquino(a)")
		Country.where(:name=>"Marshall, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Martinica").first.update(:nationality=>"-")
		Country.where(:name=>"Maurício").first.update(:nationality=>"-")
		Country.where(:name=>"Mauritânia").first.update(:nationality=>"-")
		Country.where(:name=>"México").first.update(:nationality=>"mexicano(a)")
		Country.where(:name=>"Mianmar (Birmânia)").first.update(:nationality=>"-")
		Country.where(:name=>"Micronésia").first.update(:nationality=>"-")
		Country.where(:name=>"Midway, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Moçambique").first.update(:nationality=>"moçambicano(a)")
		Country.where(:name=>"Moldávia, Repúblicada").first.update(:nationality=>"-")
		Country.where(:name=>"Mônaco").first.update(:nationality=>"monegasco(a)")
		Country.where(:name=>"Mongólia").first.update(:nationality=>"-")
		Country.where(:name=>"Montserrat, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Namíbia").first.update(:nationality=>"-")
		Country.where(:name=>"Nauru").first.update(:nationality=>"-")
		Country.where(:name=>"Nepal").first.update(:nationality=>"-")
		Country.where(:name=>"Nicarágua").first.update(:nationality=>"nicaraguense")
		Country.where(:name=>"Niger").first.update(:nationality=>"-")
		Country.where(:name=>"Nigéria").first.update(:nationality=>"-")
		Country.where(:name=>"Niue, Ilha").first.update(:nationality=>"-")
		Country.where(:name=>"Norfolk, Ilha").first.update(:nationality=>"-")
		Country.where(:name=>"Noruega").first.update(:nationality=>"norueguês(esa)")
		Country.where(:name=>"Nova Caledônia").first.update(:nationality=>"-")
		Country.where(:name=>"Nova Zelândia").first.update(:nationality=>"neozelandês(esa)")
		Country.where(:name=>"Omã").first.update(:nationality=>"-")
		Country.where(:name=>"Países Baixos (Holanda)").first.update(:nationality=>"neerlandês(esa)")
		Country.where(:name=>"Palau").first.update(:nationality=>"-")
		Country.where(:name=>"Panamá").first.update(:nationality=>"panamenho(a)")
		Country.where(:name=>"Papua Nova Guiné").first.update(:nationality=>"-")
		Country.where(:name=>"Paquistão").first.update(:nationality=>"-")
		Country.where(:name=>"Paraguai").first.update(:nationality=>"-")
		Country.where(:name=>"Peru").first.update(:nationality=>"peruano(a)")
		Country.where(:name=>"Pitcairn, Ilha").first.update(:nationality=>"-")
		Country.where(:name=>"Polinésia Francesa").first.update(:nationality=>"-")
		Country.where(:name=>"Polônia, Repúblicada").first.update(:nationality=>"polaco(a)")
		Country.where(:name=>"Porto Rico").first.update(:nationality=>"porto-riquenho(a)")
		Country.where(:name=>"Portugal").first.update(:nationality=>"português(a)")
		Country.where(:name=>"Quênia").first.update(:nationality=>"queniano")
		Country.where(:name=>"Quirguiz, República").first.update(:nationality=>"-")
		Country.where(:name=>"Reino Unido").first.update(:nationality=>"-")
		Country.where(:name=>"República Centro-Africana").first.update(:nationality=>"-")
		Country.where(:name=>"República Dominicana").first.update(:nationality=>"-")
		Country.where(:name=>"Reunião, Ilha").first.update(:nationality=>"-")
		Country.where(:name=>"Romênia").first.update(:nationality=>"-")
		Country.where(:name=>"Ruanda").first.update(:nationality=>"-")
		Country.where(:name=>"Rússia").first.update(:nationality=>"russo(a)")
		Country.where(:name=>"Saara Ocidental").first.update(:nationality=>"-")
		Country.where(:name=>"Salomão, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Samoa").first.update(:nationality=>"-")
		Country.where(:name=>"Samoa Americana").first.update(:nationality=>"-")
		Country.where(:name=>"San Marino").first.update(:nationality=>"-")
		Country.where(:name=>"Santa Helena").first.update(:nationality=>"-")
		Country.where(:name=>"Santa Lúcia").first.update(:nationality=>"-")
		Country.where(:name=>"São Cristóvão e Neves").first.update(:nationality=>"-")
		Country.where(:name=>"São Tomé e Príncipe, Ilhas").first.update(:nationality=>"são-tomense")
		Country.where(:name=>"São Vicente e Granadinas").first.update(:nationality=>"-")
		Country.where(:name=>"Senegal").first.update(:nationality=>"senegalês(esa)")
		Country.where(:name=>"Serra Leoa").first.update(:nationality=>"-")
		Country.where(:name=>"Seychelles").first.update(:nationality=>"-")
		Country.where(:name=>"Síria, República Árabe da").first.update(:nationality=>"-")
		Country.where(:name=>"Somália").first.update(:nationality=>"-")
		Country.where(:name=>"Sri Lanka").first.update(:nationality=>"-")
		Country.where(:name=>"Suazilândia").first.update(:nationality=>"suazilandês(a)")
		Country.where(:name=>"Sudão").first.update(:nationality=>"-")
		Country.where(:name=>"Suécia").first.update(:nationality=>"sueco(a)")
		Country.where(:name=>"Suíça").first.update(:nationality=>"suíço(a)")
		Country.where(:name=>"Suriname").first.update(:nationality=>"surinamês(a)")
		Country.where(:name=>"Tadjiquistão").first.update(:nationality=>"-")
		Country.where(:name=>"Tailândia").first.update(:nationality=>"tailandês")
		Country.where(:name=>"Tanzânia, República Unida da").first.update(:nationality=>"-")
		Country.where(:name=>"Tcheca, República").first.update(:nationality=>"-")
		Country.where(:name=>"Território Britânico Oc. Índico").first.update(:nationality=>"-")
		Country.where(:name=>"Timor Leste").first.update(:nationality=>"timorense")
		Country.where(:name=>"Togo").first.update(:nationality=>"-")
		Country.where(:name=>"Tonga").first.update(:nationality=>"-")
		Country.where(:name=>"Toquelau, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Trinidad e Tobago").first.update(:nationality=>"trinitário(a)-tobagense")
		Country.where(:name=>"Tunísia").first.update(:nationality=>"-")
		Country.where(:name=>"Turcas e Caicos, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Turcomenistão, República do").first.update(:nationality=>"-")
		Country.where(:name=>"Turquia").first.update(:nationality=>"turco(a)")
		Country.where(:name=>"Tuvalu").first.update(:nationality=>"-")
		Country.where(:name=>"Ucrânia").first.update(:nationality=>"ucraniano(a)")
		Country.where(:name=>"Uganda").first.update(:nationality=>"ugandense")
		Country.where(:name=>"Uruguai").first.update(:nationality=>"uruguaio(a)")
		Country.where(:name=>"Uzbequistão, República do").first.update(:nationality=>"-")
		Country.where(:name=>"Vanuatu").first.update(:nationality=>"-")
		Country.where(:name=>"Vaticano, Estado da Cidade do").first.update(:nationality=>"-")
		Country.where(:name=>"Venezuela").first.update(:nationality=>"venezuelano(a)")
		Country.where(:name=>"Vietnã").first.update(:nationality=>"vietnamita")
		Country.where(:name=>"Virgens, Ilhas(Britânicas)").first.update(:nationality=>"-")
		Country.where(:name=>"Virgens, Ilhas(E.U.A.)").first.update(:nationality=>"-")
		Country.where(:name=>"Wake, Ilha").first.update(:nationality=>"-")
		Country.where(:name=>"Wallis e Futuna, Ilhas").first.update(:nationality=>"-")
		Country.where(:name=>"Zâmbia").first.update(:nationality=>"-")
		Country.where(:name=>"Zimbábue").first.update(:nationality=>"zimbabuano(a)")
		Country.where(:name=>"Zona do Canal do Panamá").first.update(:nationality=>"-")

  end
end
