class AddNationalityDataToCountry < ActiveRecord::Migration
  def change
    Country.where(:name=>"Afeganistão").update_all(:nationality=>"afegã(o)")
    Country.where(:name=>"África do Sul").update_all(:nationality=>"sul-africano(a)")
    Country.where(:name=>"Albânia, República da").update_all(:nationality=>"albanês(esa)")
    Country.where(:name=>"Alemanha").update_all(:nationality=>"alemã(ão)")
    Country.where(:name=>"Andorra").update_all(:nationality=>"andorrano(a)")
    Country.where(:name=>"Angola").update_all(:nationality=>"angolano(a)")
    Country.where(:name=>"Anguilla").update_all(:nationality=>"anguilano(a)")
    Country.where(:name=>"Antigua e Barbuda").update_all(:nationality=>"antiguano(a)")
    Country.where(:name=>"Antilhas Holandesas").update_all(:nationality=>"-")
    Country.where(:name=>"Arábia Saudita").update_all(:nationality=>"árabe-saudita")
    Country.where(:name=>"Argélia").update_all(:nationality=>"argelino(a)")
    Country.where(:name=>"Argentina").update_all(:nationality=>"argentino(a)")
    Country.where(:name=>"Armênia, República da").update_all(:nationality=>"arménio(a)")
    Country.where(:name=>"Aruba").update_all(:nationality=>"arubano(a)")
    Country.where(:name=>"Austrália").update_all(:nationality=>"australiano(a)")
    Country.where(:name=>"Áustria").update_all(:nationality=>"austríaco(a)")
    Country.where(:name=>"Azerbaijão, Repúblicado").update_all(:nationality=>"azeri")
    Country.where(:name=>"Bahamas, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Bahrein, Ilhas").update_all(:nationality=>"barenita")
    Country.where(:name=>"Bangladesh").update_all(:nationality=>"-")
    Country.where(:name=>"Barbados").update_all(:nationality=>"barbadense")
    Country.where(:name=>"Belarus").update_all(:nationality=>"bielo-russa")
    Country.where(:name=>"Bélgica").update_all(:nationality=>"belga")
    Country.where(:name=>"Belize").update_all(:nationality=>"belizenho(a)")
    Country.where(:name=>"Benin").update_all(:nationality=>"benineseo(a)")
    Country.where(:name=>"Bermudas").update_all(:nationality=>"-")
    Country.where(:name=>"Bolívia").update_all(:nationality=>"boliviano(a)")
    Country.where(:name=>"Bósnia-Herzegovina").update_all(:nationality=>"bósnio(a)")
    Country.where(:name=>"Botsuana").update_all(:nationality=>"-")
    Country.where(:name=>"Brasil").update_all(:nationality=>"brasileiro(a)")
    Country.where(:name=>"Brunei").update_all(:nationality=>"-")
    Country.where(:name=>"Bulgária, República da").update_all(:nationality=>"búlgaro(a)")
    Country.where(:name=>"Burkina Faso").update_all(:nationality=>"-")
    Country.where(:name=>"Burundi").update_all(:nationality=>"-")
    Country.where(:name=>"Butão").update_all(:nationality=>"-")
    Country.where(:name=>"Cabo Verde, República de").update_all(:nationality=>"Cabo Verde cabo-verdiano(a)")
    Country.where(:name=>"Camarões").update_all(:nationality=>"-")
    Country.where(:name=>"Camboja").update_all(:nationality=>"cambojano(a)")
    Country.where(:name=>"Canadá").update_all(:nationality=>"canadiano(a)")
    Country.where(:name=>"Canal, Ilhas do (Jerseye Guernsey)").update_all(:nationality=>"-")
    Country.where(:name=>"Canárias, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Catar").update_all(:nationality=>"-")
    Country.where(:name=>"Cayman, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Cazaquistão, República do").update_all(:nationality=>"-")
    Country.where(:name=>"Chade").update_all(:nationality=>"-")
    Country.where(:name=>"Chile").update_all(:nationality=>"chileno(a)")
    Country.where(:name=>"China, República Popular da").update_all(:nationality=>"chinês(esa)")
    Country.where(:name=>"Chipre").update_all(:nationality=>"cipriota")
    Country.where(:name=>"Christmas, Ilha (Navidad)").update_all(:nationality=>"-")
    Country.where(:name=>"Cingapura").update_all(:nationality=>"-")
    Country.where(:name=>"Cocos (Keeling), Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Colômbia").update_all(:nationality=>"colombiano(a)")
    Country.where(:name=>"Comores, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Congo, República Democrática do").update_all(:nationality=>"-")
    Country.where(:name=>"Congo, República do").update_all(:nationality=>"Congo congolês(a)")
    Country.where(:name=>"Cook, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Coréia, Rep. Pop. Democrática da").update_all(:nationality=>"-")
    Country.where(:name=>"Coréia, República da").update_all(:nationality=>"sul-coreano(a)")
    Country.where(:name=>"Costa do Marfim").update_all(:nationality=>"Costa do Marfm marfinense")
    Country.where(:name=>"Costa Rica").update_all(:nationality=>"costa-riquenho(a)")
    Country.where(:name=>"Coveite").update_all(:nationality=>"-")
    Country.where(:name=>"Croácia, República da").update_all(:nationality=>"croata")
    Country.where(:name=>"Cuba").update_all(:nationality=>"cubano(a)")
    Country.where(:name=>"Dinamarca").update_all(:nationality=>"dinamarquês(esa)")
    Country.where(:name=>"Djibuti").update_all(:nationality=>"-")
    Country.where(:name=>"Dominica, Ilha").update_all(:nationality=>"dominiquês(esa)")
    Country.where(:name=>"Egito").update_all(:nationality=>"egípcio(a)")
    Country.where(:name=>"ElSalvador").update_all(:nationality=>"-")
    Country.where(:name=>"Emirados Árabes Unidos").update_all(:nationality=>"emiradense")
    Country.where(:name=>"Equador").update_all(:nationality=>"equatoriano(a)")
    Country.where(:name=>"Eritréia").update_all(:nationality=>"-")
    Country.where(:name=>"Escócia").update_all(:nationality=>"escocês(esa)")
    Country.where(:name=>"Eslovaca, República").update_all(:nationality=>"-")
    Country.where(:name=>"Eslovênia, República da").update_all(:nationality=>"Eslovénia esloveno(a)")
    Country.where(:name=>"Espanha").update_all(:nationality=>"espanhol(a)")
    Country.where(:name=>"Estados Unidos").update_all(:nationality=>"norte-americano(a)")
    Country.where(:name=>"Estônia, República da").update_all(:nationality=>"-")
    Country.where(:name=>"Etiópia").update_all(:nationality=>"etíope")
    Country.where(:name=>"Falkland (Ilhas Malvinas)").update_all(:nationality=>"-")
    Country.where(:name=>"Feroe, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Fiji").update_all(:nationality=>"-")
    Country.where(:name=>"Filipinas").update_all(:nationality=>"filipino")
    Country.where(:name=>"Finlândia").update_all(:nationality=>"finlandês(esa)")
    Country.where(:name=>"Formosa (Taiwan)").update_all(:nationality=>"-")
    Country.where(:name=>"França").update_all(:nationality=>"francês(esa)")
    Country.where(:name=>"Gabão").update_all(:nationality=>"-")
    Country.where(:name=>"Gales, País de").update_all(:nationality=>"-")
    Country.where(:name=>"Gâmbia").update_all(:nationality=>"gambiano(a)")
    Country.where(:name=>"Gana").update_all(:nationality=>"ganês(a)")
    Country.where(:name=>"Geórgia, República da").update_all(:nationality=>"georgiano(a)")
    Country.where(:name=>"Gibraltar").update_all(:nationality=>"-")
    Country.where(:name=>"Grã-Bretanha").update_all(:nationality=>"-")
    Country.where(:name=>"Granada").update_all(:nationality=>"-")
    Country.where(:name=>"Grécia").update_all(:nationality=>"grego(a)")
    Country.where(:name=>"Groenlândia").update_all(:nationality=>"-")
    Country.where(:name=>"Guadalupe").update_all(:nationality=>"guadalupense")
    Country.where(:name=>"Guam").update_all(:nationality=>"-")
    Country.where(:name=>"Guatemala").update_all(:nationality=>"guatemalteco(a)")
    Country.where(:name=>"Guiana").update_all(:nationality=>"-")
    Country.where(:name=>"Guiana Francesa").update_all(:nationality=>"-")
    Country.where(:name=>"Guiné").update_all(:nationality=>"-")
    Country.where(:name=>"Guiné-Bissau").update_all(:nationality=>"-")
    Country.where(:name=>"Guiné-Equatorial").update_all(:nationality=>"-")
    Country.where(:name=>"Haiti").update_all(:nationality=>"-")
    Country.where(:name=>"Holanda (PaísesBaixos)").update_all(:nationality=>"-")
    Country.where(:name=>"Honduras").update_all(:nationality=>"hondurenho(a)")
    Country.where(:name=>"HongKong, Região Adm. Especial").update_all(:nationality=>"honconguês(esa)")
    Country.where(:name=>"Hungria, Repúblicada").update_all(:nationality=>"húngaro(a)")
    Country.where(:name=>"Iêmen").update_all(:nationality=>"-")
    Country.where(:name=>"Índia").update_all(:nationality=>"indiano(a)")
    Country.where(:name=>"Indonésia").update_all(:nationality=>"indonésio")
    Country.where(:name=>"Inglaterra").update_all(:nationality=>"inglês(esa)")
    Country.where(:name=>"Irã, República Islâmica do").update_all(:nationality=>"Irã iraniano(a)")
    Country.where(:name=>"Iraque").update_all(:nationality=>"iraquiano(a)")
    Country.where(:name=>"Irlanda").update_all(:nationality=>"irlandês(a)")
    Country.where(:name=>"Irlanda do Norte").update_all(:nationality=>"norte irlandês(a)")
    Country.where(:name=>"Islândia").update_all(:nationality=>"islandês(esa)")
    Country.where(:name=>"Israel").update_all(:nationality=>"israelita")
    Country.where(:name=>"Itália").update_all(:nationality=>"italiano(a)")
    Country.where(:name=>"Iugoslávia, República Fed. da").update_all(:nationality=>"-")
    Country.where(:name=>"Jamaica").update_all(:nationality=>"-")
    Country.where(:name=>"Japão").update_all(:nationality=>"-")
    Country.where(:name=>"Johnston, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Jordânia").update_all(:nationality=>"-")
    Country.where(:name=>"Kiribati").update_all(:nationality=>"-")
    Country.where(:name=>"Laos, Rep. Pop. Democrática do").update_all(:nationality=>"laociano(a)")
    Country.where(:name=>"Lebuan").update_all(:nationality=>"-")
    Country.where(:name=>"Lesoto").update_all(:nationality=>"-")
    Country.where(:name=>"Letônia, Repúblicada").update_all(:nationality=>"-")
    Country.where(:name=>"Líbano").update_all(:nationality=>"-")
    Country.where(:name=>"Libéria").update_all(:nationality=>"-")
    Country.where(:name=>"Líbia").update_all(:nationality=>"líbio(a)")
    Country.where(:name=>"Liechtenstein").update_all(:nationality=>"-")
    Country.where(:name=>"Lituânia, República da").update_all(:nationality=>"lituano(a)")
    Country.where(:name=>"Luxemburgo").update_all(:nationality=>"-")
    Country.where(:name=>"Macau").update_all(:nationality=>"-")
    Country.where(:name=>"Macedônia").update_all(:nationality=>"-")
    Country.where(:name=>"Madagascar").update_all(:nationality=>"-")
    Country.where(:name=>"Madeira, Ilhada").update_all(:nationality=>"-")
    Country.where(:name=>"Malásia").update_all(:nationality=>"-")
    Country.where(:name=>"Malavi").update_all(:nationality=>"-")
    Country.where(:name=>"Maldivas").update_all(:nationality=>"-")
    Country.where(:name=>"Máli").update_all(:nationality=>"maliano")
    Country.where(:name=>"Malta").update_all(:nationality=>"-")
    Country.where(:name=>"Man, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Marianas do Norte").update_all(:nationality=>"-")
    Country.where(:name=>"Marrocos").update_all(:nationality=>"marroquino(a)")
    Country.where(:name=>"Marshall, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Martinica").update_all(:nationality=>"-")
    Country.where(:name=>"Maurício").update_all(:nationality=>"-")
    Country.where(:name=>"Mauritânia").update_all(:nationality=>"-")
    Country.where(:name=>"México").update_all(:nationality=>"mexicano(a)")
    Country.where(:name=>"Mianmar (Birmânia)").update_all(:nationality=>"-")
    Country.where(:name=>"Micronésia").update_all(:nationality=>"-")
    Country.where(:name=>"Midway, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Moçambique").update_all(:nationality=>"moçambicano(a)")
    Country.where(:name=>"Moldávia, Repúblicada").update_all(:nationality=>"-")
    Country.where(:name=>"Mônaco").update_all(:nationality=>"monegasco(a)")
    Country.where(:name=>"Mongólia").update_all(:nationality=>"-")
    Country.where(:name=>"Montserrat, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Namíbia").update_all(:nationality=>"-")
    Country.where(:name=>"Nauru").update_all(:nationality=>"-")
    Country.where(:name=>"Nepal").update_all(:nationality=>"-")
    Country.where(:name=>"Nicarágua").update_all(:nationality=>"nicaraguense")
    Country.where(:name=>"Niger").update_all(:nationality=>"-")
    Country.where(:name=>"Nigéria").update_all(:nationality=>"-")
    Country.where(:name=>"Niue, Ilha").update_all(:nationality=>"-")
    Country.where(:name=>"Norfolk, Ilha").update_all(:nationality=>"-")
    Country.where(:name=>"Noruega").update_all(:nationality=>"norueguês(esa)")
    Country.where(:name=>"Nova Caledônia").update_all(:nationality=>"-")
    Country.where(:name=>"Nova Zelândia").update_all(:nationality=>"neozelandês(esa)")
    Country.where(:name=>"Omã").update_all(:nationality=>"-")
    Country.where(:name=>"Países Baixos (Holanda)").update_all(:nationality=>"neerlandês(esa)")
    Country.where(:name=>"Palau").update_all(:nationality=>"-")
    Country.where(:name=>"Panamá").update_all(:nationality=>"panamenho(a)")
    Country.where(:name=>"Papua Nova Guiné").update_all(:nationality=>"-")
    Country.where(:name=>"Paquistão").update_all(:nationality=>"-")
    Country.where(:name=>"Paraguai").update_all(:nationality=>"-")
    Country.where(:name=>"Peru").update_all(:nationality=>"peruano(a)")
    Country.where(:name=>"Pitcairn, Ilha").update_all(:nationality=>"-")
    Country.where(:name=>"Polinésia Francesa").update_all(:nationality=>"-")
    Country.where(:name=>"Polônia, Repúblicada").update_all(:nationality=>"polaco(a)")
    Country.where(:name=>"Porto Rico").update_all(:nationality=>"porto-riquenho(a)")
    Country.where(:name=>"Portugal").update_all(:nationality=>"português(a)")
    Country.where(:name=>"Quênia").update_all(:nationality=>"queniano")
    Country.where(:name=>"Quirguiz, República").update_all(:nationality=>"-")
    Country.where(:name=>"Reino Unido").update_all(:nationality=>"-")
    Country.where(:name=>"República Centro-Africana").update_all(:nationality=>"-")
    Country.where(:name=>"República Dominicana").update_all(:nationality=>"-")
    Country.where(:name=>"Reunião, Ilha").update_all(:nationality=>"-")
    Country.where(:name=>"Romênia").update_all(:nationality=>"-")
    Country.where(:name=>"Ruanda").update_all(:nationality=>"-")
    Country.where(:name=>"Rússia").update_all(:nationality=>"russo(a)")
    Country.where(:name=>"Saara Ocidental").update_all(:nationality=>"-")
    Country.where(:name=>"Salomão, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Samoa").update_all(:nationality=>"-")
    Country.where(:name=>"Samoa Americana").update_all(:nationality=>"-")
    Country.where(:name=>"San Marino").update_all(:nationality=>"-")
    Country.where(:name=>"Santa Helena").update_all(:nationality=>"-")
    Country.where(:name=>"Santa Lúcia").update_all(:nationality=>"-")
    Country.where(:name=>"São Cristóvão e Neves").update_all(:nationality=>"-")
    Country.where(:name=>"São Tomé e Príncipe, Ilhas").update_all(:nationality=>"são-tomense")
    Country.where(:name=>"São Vicente e Granadinas").update_all(:nationality=>"-")
    Country.where(:name=>"Senegal").update_all(:nationality=>"senegalês(esa)")
    Country.where(:name=>"Serra Leoa").update_all(:nationality=>"-")
    Country.where(:name=>"Seychelles").update_all(:nationality=>"-")
    Country.where(:name=>"Síria, República Árabe da").update_all(:nationality=>"-")
    Country.where(:name=>"Somália").update_all(:nationality=>"-")
    Country.where(:name=>"Sri Lanka").update_all(:nationality=>"-")
    Country.where(:name=>"Suazilândia").update_all(:nationality=>"suazilandês(a)")
    Country.where(:name=>"Sudão").update_all(:nationality=>"-")
    Country.where(:name=>"Suécia").update_all(:nationality=>"sueco(a)")
    Country.where(:name=>"Suíça").update_all(:nationality=>"suíço(a)")
    Country.where(:name=>"Suriname").update_all(:nationality=>"surinamês(a)")
    Country.where(:name=>"Tadjiquistão").update_all(:nationality=>"-")
    Country.where(:name=>"Tailândia").update_all(:nationality=>"tailandês")
    Country.where(:name=>"Tanzânia, República Unida da").update_all(:nationality=>"-")
    Country.where(:name=>"Tcheca, República").update_all(:nationality=>"-")
    Country.where(:name=>"Território Britânico Oc. Índico").update_all(:nationality=>"-")
    Country.where(:name=>"Timor Leste").update_all(:nationality=>"timorense")
    Country.where(:name=>"Togo").update_all(:nationality=>"-")
    Country.where(:name=>"Tonga").update_all(:nationality=>"-")
    Country.where(:name=>"Toquelau, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Trinidad e Tobago").update_all(:nationality=>"trinitário(a)-tobagense")
    Country.where(:name=>"Tunísia").update_all(:nationality=>"-")
    Country.where(:name=>"Turcas e Caicos, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Turcomenistão, República do").update_all(:nationality=>"-")
    Country.where(:name=>"Turquia").update_all(:nationality=>"turco(a)")
    Country.where(:name=>"Tuvalu").update_all(:nationality=>"-")
    Country.where(:name=>"Ucrânia").update_all(:nationality=>"ucraniano(a)")
    Country.where(:name=>"Uganda").update_all(:nationality=>"ugandense")
    Country.where(:name=>"Uruguai").update_all(:nationality=>"uruguaio(a)")
    Country.where(:name=>"Uzbequistão, República do").update_all(:nationality=>"-")
    Country.where(:name=>"Vanuatu").update_all(:nationality=>"-")
    Country.where(:name=>"Vaticano, Estado da Cidade do").update_all(:nationality=>"-")
    Country.where(:name=>"Venezuela").update_all(:nationality=>"venezuelano(a)")
    Country.where(:name=>"Vietnã").update_all(:nationality=>"vietnamita")
    Country.where(:name=>"Virgens, Ilhas(Britânicas)").update_all(:nationality=>"-")
    Country.where(:name=>"Virgens, Ilhas(E.U.A.)").update_all(:nationality=>"-")
    Country.where(:name=>"Wake, Ilha").update_all(:nationality=>"-")
    Country.where(:name=>"Wallis e Futuna, Ilhas").update_all(:nationality=>"-")
    Country.where(:name=>"Zâmbia").update_all(:nationality=>"-")
    Country.where(:name=>"Zimbábue").update_all(:nationality=>"zimbabuano(a)")
    Country.where(:name=>"Zona do Canal do Panamá").update_all(:nationality=>"-")
  end
end
