class Role < ActiveRecord::Base

  ROLE_DESCONHECIDO = 1
  ROLE_COORDENACAO = 2
  ROLE_SECRETARIA_BOLSAS = 3
  ROLE_SECRETARIA_MATRICULAS = 4
  ROLE_SECRETARIA_MANUTENCAO_MATRICULAS = 5
  ROLE_PROFESSOR = 6
  ROLE_ALUNO = 7
  ROLE_ADMINISTRADOR = 8
end
