# This workflow will install a prebuilt Ruby version, install dependencies, and run tests.
name: "Ruby on Rails CI"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      BUNDLE_WITHOUT: production
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
          install-chromedriver: false
        
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 1 # Increment this number if you need to re-download cached gems

      - name: Set up database schema
        run: bundle exec rake db:test:prepare --trace
        
      - name: Run tests
        run: bundle exec rspec
        
      - name: Publish code coverage
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/.resultset.json

  smoke-test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: production
      SECRET_KEY_BASE: chave_falsa_apenas_para_o_boot_do_smoke_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install sendmail
        run: sudo apt-get install -y sendmail

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 1

      - name: Run smoke test
        run: bundle exec rake smoke_test:all
